### ISSUE TITLE
Support editing Directory.Packages.props in context

### ISSUE THREAD

**Issue by Bertk** [mhutch/MonoDevelop.MSBuildEditor#105]
**MSBuild Editor** does not support [Central Package Management (CPM)](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management) and creates message "Possible unused or misspelled property".

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/2315215/fca01241-752a-4065-932e-eb10cfaab601)

**Comment by mhutch** [comment]
I assume this is in the `Directory.Packages.props` file?

The issue is that the `Directory.Packages.props` file doesn't import any targets for which we could locate schemas - it's expected to be imported by another file, and the context comes from the file that imports it.

We either need to special-case `Directory.Packages.props`, or add support for editing it in the context of a project file.

**Comment by kzu** [comment]
Same thing happens for other targets imported by various extension points in MSBuid. Here's another one to be imported by one of the common targets, for example:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/169707/ad0fd740-112d-4942-a56a-260ec74d2efc)

I'd say that the "built-in" stuff defined in the schema matching the xmlns, should perhaps always be included? i.e. the `Message` task is defined in C:\Program Files\Microsoft Visual Studio\2022\Preview\Xml\Schemas\1033\MSBuild\Microsoft.Build.Commontypes.xsd
