### ISSUE TITLE
The value is not a valid GUID format

### ISSUE THREAD

**Issue by Suchiman** [mhutch/MonoDevelop.MSBuildEditor#174]
The extension erroneously warns that
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/7110884/424c23a6-c8ca-4182-85a4-760eb0d36935)
this is due to this code requiring the B format for some reason
https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/1079e36b274da6d8f97caaa1ddb7aeb42b390882/MonoDevelop.MSBuild/Language/MSBuildDocumentValidator.cs#L636-L637
which only permits guids using hyphens AND curly braces
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/7110884/43fc64bd-8f13-456d-b84c-dd56c998f939)
Unless there's some reason that i'm unaware of, i would suggest just switching to `Guid.TryParse` to recognize any valid guid.

**Comment by mhutch** [comment]
I believe it did that because some of the properties typed as `guid` did require that format, so I'll need to check the other uses of that type. From an MSBuild perspective they're just strings and it's up to the tasks to parse them, so it's difficult to be truly consistent. I'll change the `guid` type to allow any format supported by `TryParse`, but we may need another type to represent the constrained GUID format for some other properties.

**Comment by mhutch** [comment]
Per #181 it turns out this doesn't actually have to be a GUID at all, so I updated the schema to mark it as a string.

However, I went ahead and [implemented the analyzer hints](https://github.com/mhutch/MonoDevelop.MSBuildEditor/commit/053b28085aaa32f87328bc541a09b148a8d45a55), so `guid` will now allow anything supported by `Guid.TryParse()`, and I updated various other GUIDs in the schema to use `"analyzerHints": { "GuidFormat": "B" }`
