### ISSUE TITLE
Some TFM (Target Framework Markup) does not recognized

### ISSUE THREAD

**Issue by wherewhere** [mhutch/MonoDevelop.MSBuildEditor#213]
It recognizes net20 but not recognizes net2.0.
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/27689196/dc46db40-373d-4ef6-ad22-712ba16f42f4)
And this
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/27689196/3890b30f-a25c-4503-8409-26e9d9d28fcf)
And more...
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/27689196/20c7be1e-284a-4dad-937d-54291415585c)
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/27689196/473a8f31-56b6-4e21-9882-40e5b36bc013)

**Comment by mhutch** [comment]
This should be fixed by #218 with the following exceptions:

* As far as I know, the `Client` profile does not exist for .NET 2.0, so I did not add it.
* For .NET versions older than `5.0`, the canonical form has no periods i.e. `net481`, not `net4.8.1`. The latter form is now valid but is not widely used.
* According to the docs, `netcore50` is equivalent to `uap10.0` and the latter is preferred
* I don't think `native` is a TFM you can build against, it's for NuGet packages that contain native assets?

**Comment by wherewhere** [comment]
.NET/WinRT for C++ projects should target to native.

**Comment by mhutch** [comment]
I did add `netcore50` as a separate TFM shortname so that the editor can represent it in the form it was specified 🙂 https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/218/files#diff-f6022ed4ae947a7d938bee206bef2e5c20afd3f6a32a4b69e2aaffcc3cba1b2aR244

However, note that the docs https://learn.microsoft.com/en-us/dotnet/standard/frameworks describe some frameworks as equivalent, and some as deprecated in favor of equivalent frameworks.

Some of this equivalency is built into NuGet. For example, the short TFM `win8` las the long form `Windows,Version=v8.0`, and the short TFM `netcore45` has the long form `.NETCore,Version=v4.5`. However, NuGet considers them to be equivalent even though they are not identical: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs#L129

The case of `uap0.0` and `netcore50` is an outlier as the docs say they are equivalent but NuGet does not. I'm not sure if this is intentional.

Anyways, the editor doesn't currently have any special behavior for equivalent TFMs, and treats them independently. It might be nice to have some kind of tooltip for equivalency and aliases, but I guess that will require more thought.

**Comment by mhutch** [comment]
Regarding treatment of `native`, I don't want to build in behavior without having a good definition of what it should mean outside of a NuGet package.

The link you provide for `native` isn't internally consistent. For NuGet restore, these targets leave `native` a `native` (i.e. `native,Version=v0.0`) or treat it as an alias for `uap10.0` depending on whether it's a design-time build or not:

```xml
<NuGetTargetMoniker Condition="'$(DesignTimeBuild)' == 'true'">native</NuGetTargetMoniker>
<NuGetTargetMoniker Condition="'$(DesignTimeBuild)' != 'true'">UAP,Version=v10.0</NuGetTargetMoniker>
```

But for all other purposes, e.g. reference assembly pack resolution, it treats `native` an alias for `.UAP,Version=v10.0.19041.0`, then immediately overrides it to `.NETCore,Version=v5.0` instead:

```xml
<TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
...
<TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
...
<TargetFrameworkIdentifier>.NETCore</TargetFrameworkIdentifier>
<TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
```

In future I'd like to move away from hardcoding the TFMs in MSBuild Editor like this, and instead allow TFMs to be defined in the `.buildschema.json` MSBuild schema files for the targets files that support/handle those TFMs. This would allow targets like these to define whatever TFMs they need without affecting completion/validation for projects that don't use those targets.

**Comment by wherewhere** [comment]
So is that any way to write comments in MSBuild XML. Just like comments in C# and other languages.

**Comment by wherewhere** [comment]
And how about this pr #219

**Comment by wherewhere** [comment]
@mhutch Missing `net-cf` which is `.NET Compact Framework`.
https://www.nuget.org/packages?q=&tfms=net3.5-cf
`sl-wp` which is `Windows Phone`.
https://www.nuget.org/packages?q=&tfms=sl4-wp71
