### ISSUE TITLE
Tooltips inconsistency

### ISSUE THREAD

**Issue by kant2002** [mhutch/MonoDevelop.MSBuildEditor#82]
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\Microsoft.FSharp.NetSdk.props

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/4257079/b4dad50d-1d5e-4d80-bc23-a4d9ac6370fa)
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/4257079/29ddd6aa-cfdf-4712-b2f6-d04741cc4cf8)

Why there no Defaults for `TreatWarningsAsErrors`? 

Switch to C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.props
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/4257079/a1fed7e5-b93d-44cd-a56b-8a7e4687e93f)
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/4257079/84e93d67-1408-46a7-97c0-74f9f12b05e8)

**Comment by mhutch** [comment]
This is due to https://github.com/mhutch/MonoDevelop.MSBuildEditor/issues/89.

Type information and documentation come from schemas that are associated with a targets file or SDK. If the file you have open transitively imports a targets/SDK that has a schema, then the schema is loaded.

In this case, the file you are editing is expected to be imported by a file that imports the targets/sdk with the schema. So until we have a way to say "I want to edit this file in the context of a project", there will be cases like this.
